### ISSUE TITLE
Koala config

### ISSUE THREAD

**Issue by arnaudjnn** [rakeshpatra/instagram_graph_api#2]
Do we have to add the Koala config before to use this gem ?

https://github.com/arsduo/koala#configuration

I tried to generate a token via https://developers.facebook.com/tools/explorer but the client.ig_business_accounts hash is empty.

Let us know

**Comment by rakeshpatra** [comment]
You can directly use your access_token, doing the configuration is not mandatory. 

Regarding ig_business_accounts,  are those appearing on Facebook GraphAPI Explorer?
