### ISSUE TITLE
Added new endpoints

### ISSUE THREAD

**Issue by ciromine** [rakeshpatra/instagram_graph_api#3]
Hi! until a few days Instagram added new endpoints to his graph-api (for example https://developers.facebook.com/docs/instagram-api/hashtag-search) is possible in the future, add this new endpoints?

Thanks a lot!

**Comment by rakeshpatra** [comment]
Yes,  sure.

**Comment by storrence88** [comment]
@rakeshpatra - Has the new endpoint for `hashtag-search` been added?

**Comment by rakeshpatra** [comment]
> @rakeshpatra - Has the new endpoint for `hashtag-search` been added?

@storrence88  Not yet, hashtag-search needs app approval, so couldn't integrate.

**Comment by MONAKA0721** [comment]
@rakeshpatra 
Hi! Nice to meet you.
Has the new endpoint for Graph API's `hashtag-search` been added?
I understand that Facebook's app needs access approval to use that, but this gem can be used assuming that app got approval, can't it ?
If can, I want to contribute for the new endpoint function of this gem.
I am very sorry for my poor English.

**Comment by rakeshpatra** [comment]
Hey,

I would be more glad if someone can help me adding the new endpoints to the
gem, what I would need is a token with that permission so that we can test
and implement the feature.

You can always reach me, I will me happy to help as much as I can.

Thanks,
Rakesh

**Comment by MONAKA0721** [comment]
Thank you for your reply.
I'll take access token and try.
To contribute, I need to fork and create PR, doesn't it ?

**Comment by rakeshpatra** [comment]
Yes, also if you can share the token with me I can add those endpoint to
the gem.

**Comment by MONAKA0721** [comment]
@rakeshpatra 
I have taken instagram_business_account's id & access_token, so how can I share them with you.

**Comment by rakeshpatra** [comment]
You can send me over email, else you can add me as a tester Or developer to
the Facebook app of your project.

My email id: rakesh.patra93@gmail.com

**Comment by rakeshpatra** [comment]
Closing this #11 adds the endpoint to the gem.
