### ISSUE TITLE
#<InstagramGraphApi::Client:0x00007f975faf1a38>

### ISSUE THREAD

**Issue by arnaudjnn** [rakeshpatra/instagram_graph_api#4]
When I use InstagramGraphApi.client(ACCESS_TOKEN), I receive #<InstagramGraphApi::Client:0x00007f975faf1a38> instead the client hash.
It worked before and I change nothing, can you check if there is a gem error?

**Comment by rakeshpatra** [comment]
Yes, it will give a InstagramGraphiApi::Client object, you can call the required methods on that.

**Comment by rakeshpatra** [comment]
Unable to re-produce.
