### ISSUE TITLE
Can we pull basic information of a non-business instagram account using this gem?

### ISSUE THREAD

**Issue by akhil-gautam** [rakeshpatra/instagram_graph_api#6]
Can we pull basic information of a non-business instagram account using this gem?
Basic info:
- follower count
- bio
- some other basic info

**Comment by rakeshpatra** [comment]
Yes, this feature has been added to the latest release, you can use the following method.
`client.connected_ig_accounts`

Thanks

**Comment by akhil-gautam** [comment]
Awesome..
