### ISSUE TITLE
client.connected_ig_accounts or client.ig_business_accounts  response empty []

### ISSUE THREAD

**Issue by NexusMTO** [rakeshpatra/instagram_graph_api#9]
I use App mode dev with account evaluate instagram  

client.connected_ig_accounts or client.ig_business_accounts 

 response empty []

**Comment by rakeshpatra** [comment]
@ZephiroRB May be you will have to check if the access_token has correct permission to view those data.

**Comment by himrock922** [comment]
@ZephiroRB 

Hi.ZephiroRB.
Maybe, Maybe, your app unsupported
yet, that some scope must valid to execute connected_ig_accounts or ig_business_sccounts.

For Example...

config/initialize/devise.rb(this is sample file, its support for facebook oauth via devise)

```
  config.omniauth :facebook, Settings.facebook.client_id,
                  Settings.facebook.client_secret,
                  scope: "pages_show_list, instagram_basic",
                  callback_url: Settings.facebook_oauth2_callback,
                  client_options: {
                    site: 'https://graph.facebook.com/v7.0',
                    authorize_url: "https://www.facebook.com/v7.0/dialog/oauth"
                  }
```
